# Ce fichier fonctionne un peu comme une recette
version: '3.7'

services:
  postgres:
    # image : "recette" créée par une entreprise pour l'installation de postgres sur un système Linux
    #  Cette image possède toutes les commandes nécessaires pour cette installation/configuration
    image: bitnami/postgresql:latest
    # Redirection des ports, le chiffre avant les ":" correspond à localhost:5432 de la machine hôte
    # le chiffre après les ":" correspond au port du container qui sera appelé par notre machine (mapping des ports)
    ports:
      - '5432:5432'
    #  Variables d'environnement nécessaires pour se connecter à la bdd postgres
    environment: 
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=polls
    # volumes : comme un storage => même quand le container sera arrêté, les données restent sauvegardés dans ce volume
    # polls_pg_data : correspond au nom du dossier où les données vont être stockées dans le container, on les définis dans la propriété volumes ci-dessous
    volumes:
      - polls_pg_data:/bitnami/postgresql

  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    volumes: 
      - 'polls_redis_data:/bitnami/redis/data'

#  dossiers "cachés" dans le container docker
volumes:
  polls_pg_data:
  polls_redis_data: